import { StyleSheet } from "react-native-unistyles";

export const styles = StyleSheet.create((theme) => ({
  root: {
    flex: 1,
    backgroundColor: theme.colors.background.default,
  },
  mediaContainer: {
    position: "absolute",
    left: 0,
    right: 0,
    backgroundColor: theme.colors.background.default,
    overflow: "hidden",
    zIndex: 10,
  },
  mediaItem: {
    flex: 1,
    backgroundColor: theme.colors.background.default,
    alignItems: "center",
    justifyContent: "center",
  },
  carouselItem: {
    flex: 1,
  },
  mediaInner: {
    width: "100%",
    height: "100%",
  },
  mediaPreviewOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: theme.colors.background.default,
  },
  header: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: theme.spacing.sm,
    backgroundColor: theme.colors.background.default,
    zIndex: 20,
  },
  headerBtn: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  headerCenter: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  compactRow: {
    position: "absolute",
    left: theme.spacing.sm,
    right: theme.spacing.sm,
    bottom: theme.spacing.sm,
    flexDirection: "row",
    alignItems: "center",
    zIndex: 10,
  },
  compactBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(0,0,0,0.55)",
    alignItems: "center",
    justifyContent: "center",
  },
  dotsRow: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "rgba(255,255,255,0.4)",
  },
  dotActive: {
    backgroundColor: "#fff",
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  footerOverlay: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: theme.colors.background.default,
    zIndex: 15,
  },
  footerBlock: {
    paddingHorizontal: theme.spacing.md,
    paddingTop: theme.spacing.sm,
    paddingBottom: theme.spacing.sm,
  },
  authorRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  authorRowFull: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  followBtn: {
    paddingHorizontal: 12,
    height: 22,
    borderRadius: 11,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  followMenuOption: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  bodyRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 4,
  },
  controlsRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 10,
  },
  ctrlBtn: {
    width: 28,
    height: 28,
    alignItems: "center",
    justifyContent: "center",
  },
  seekTrack: {
    height: 14,
    justifyContent: "center",
  },
  seekTrackBg: {
    height: 3,
    borderRadius: 2,
    backgroundColor: "rgba(255,255,255,0.3)",
  },
  seekTrackFill: {
    position: "absolute",
    left: 0,
    height: 3,
    borderRadius: 2,
  },
  seekKnob: {
    position: "absolute",
    width: 14,
    height: 14,
    borderRadius: 7,
  },
  actionsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 12,
  },
  actionGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing.md,
  },
  actionBtn: {
    flexDirection: "row",
    alignItems: "center",
  },
  inputDock: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: theme.colors.background.default,
    borderTopWidth: 1,
    borderTopColor: theme.colors.border.subtle,
    zIndex: 40,
  },
  commentsList: {
    position: "absolute",
    left: 0,
    right: 0,
    zIndex: 1,
  },
  fixedHandleArea: {
    position: "absolute",
    left: 0,
    right: 0,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
    borderTopWidth: StyleSheet.hairlineWidth,
  },
  sheetHeader: {
    paddingHorizontal: theme.spacing.md,
    paddingTop: 4,
  },
  handleBar: {
    alignSelf: "center",
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: "rgba(127,127,127,0.5)",
  },
  dividerLine: {
    height: StyleSheet.hairlineWidth,
    marginVertical: 8,
  },
  dividerThick: {
    height: 5,
    marginHorizontal: -theme.spacing.md, // span past the sheetHeader padding
    marginTop: 12,
    marginBottom: 8,
  },
  mdNoTrailingMargin: {
    marginTop: 4,
    // MarkdownContent's last paragraph has marginBottom: theme.spacing.md
    // which produces a large visible gap before the next element. Clip it.
    marginBottom: -16,
    overflow: "hidden",
  },
  sheetPostInfo: {
    paddingVertical: 2,
  },
  threadReminderCard: {
    marginTop: theme.spacing.md,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.sm,
    borderRadius: theme.radius.md,
    backgroundColor: theme.colors.background.subtle,
    borderLeftWidth: 3,
    borderLeftColor: theme.colors.primary[500],
    gap: theme.spacing.sm,
  },
  threadReminderHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing.xs,
  },
  threadReminderTitle: {
    flexShrink: 1,
  },
  threadReminderActionsRow: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: theme.spacing.sm,
    width: "100%",
  },
  threadReminderButtonSlot: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "50%",
    minWidth: 0,
    maxWidth: "50%",
  },
  threadReminderButton: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: 8,
    borderRadius: theme.radius.md,
    borderWidth: 1,
    borderColor: theme.colors.border.default,
    backgroundColor: theme.colors.background.default,
    minHeight: 36,
  },
  threadReminderButtonPressed: {
    opacity: 0.7,
  },
  threadReminderButtonDisabled: {
    opacity: 0.5,
    backgroundColor: theme.colors.background.subtle,
  },
  commentsTitle: {
    marginTop: 4,
    marginBottom: 4,
  },
  contextSkeletonList: {
    paddingVertical: theme.spacing.sm,
    paddingHorizontal: theme.spacing.md,
    gap: theme.spacing.md,
  },
  contextSkeletonRow: {
    gap: 8,
  },
  contextSkeletonHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  contextSkeletonAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: theme.colors.background.subtle,
  },
  contextSkeletonName: {
    width: 104,
    height: 10,
    borderRadius: 5,
    backgroundColor: theme.colors.background.subtle,
  },
  contextSkeletonLineFull: {
    width: "100%",
    height: 12,
    borderRadius: 6,
    backgroundColor: theme.colors.background.subtle,
  },
  contextSkeletonLineShort: {
    width: "72%",
    height: 12,
    borderRadius: 6,
    backgroundColor: theme.colors.background.subtle,
  },
  emptyState: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 24,
    paddingHorizontal: theme.spacing.lg,
  },
}));
